config/routes.rb
DeviseApp::Application.routes.draw do
	
	
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  root 'static_pages#home'
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  match '/home', to: 'static_pages#home',	 	via: 'get'
  match '/help', to: 'static_pages#help',	 	via: 'get'
  match '/contact', to: 'static_pages#contact',	 	via: 'get'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by GreenGrass
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Bloodshot", root_path, id: "logo" %>
      <ul class = "nav pull-left">
      <li class="round-image-50">       <%= link_to image_tag("logo.jpg", alt: "Bloodshot"), root_path %></li>
      </ul><nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            
                <li><%= link_to "Profile", current_user %></li>
                 <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
		
                <li class="divider"></li>
                <li>
                <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
		
              </ul>
		
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body  style="background-color: #e9e9e9";>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>